### ISSUE TITLE
error when I tried with validation of Irfiler dataset

### ISSUE THREAD

**Issue by lunasdejavu** [duanzhiihao/RAPiD#1]
since I can't find the Mirror World dataset and only have CEDOFF dataset,
I modified the code :
```
    elif args.dataset == 'H1H2':
        videos = [ 'all_off',
                  'lunch1', 'lunch2', 'lunch3', 'edge_cases', 'irill', 'high_activity']
        # if args.high_resolution:
        #     videos += ['All_off', 'IRfilter', 'IRill']
        train_img_dir = [f'/data/datasets/fisheye/cepdof/{s}/' for s in videos]
        train_json = [f'/data/datasets/fisheye/cepdof/annotations/{s}.json' for s in videos]
        val_img_dir = '/data/datasets/fisheye/cepdof/irfilter/'
        val_json = '/data/datasets/fisheye/cepdof/annotations/irfilter.json'
```
` python3 train.py --model=rapid_pL1 --backbone=res34 --dataset=H1H2 --batch_size=8 --high_resolution`
but it showed the error
```
Traceback (most recent call last):
  File "train.py", line 232, in <module>
    dts = model_eval.detect_imgSeq(val_img_dir, input_size=target_size)
  File "/data/workspace/willy_sung/RAPiD/utils/MWtools.py", line 66, in evaluate_dtList
    self._accumulate(**kwargs)
  File "/data/workspace/willy_sung/RAPiD/utils/MWtools.py", line 186, in _accumulate
    assert ((tp_sum[:,-1] + fp_sum[:,-1]) == num_dt).all()
IndexError: index -1 is out of bounds for dimension 1 with size 0
```
I check the  function `_prepare()` in  `class MWeval()`,
it seems that the format of the json file in MW is coco format like the one incepdof

**Comment by lunasdejavu** [comment]
I tried to continue for the first iterator without evaluation,then I found 
the log of training data is weird :
```
Total time: 1:45:02.388909, iter: 0:00:12.004550, epoch: 3:04:53.664582
[Iteration 523] [learning rate 0.0001] [Total loss 550.51] [img size 640]
level_20 total 4 objects: xy/gt 1.427, wh/gt 0.196, angle/gt 0.558, conf 33.780
level_40 total 24 objects: xy/gt 1.481, wh/gt 0.309, angle/gt 0.555, conf 177.896
level_80 total 25 objects: xy/gt 1.408, wh/gt 0.193, angle/gt 0.820, conf 219.820
iter_i 524

Total time: 1:45:17.027946, iter: 0:00:12.009559, epoch: 3:04:58.277775
[Iteration 524] [learning rate 0.0001] [Total loss 654.98] [img size 640]
level_20 total 6 objects: xy/gt 1.444, wh/gt 0.226, angle/gt 0.596, conf 44.437
level_40 total 26 objects: xy/gt 1.392, wh/gt 0.288, angle/gt 0.959, conf 192.055
level_80 total 31 objects: xy/gt 1.421, wh/gt 0.256, angle/gt 0.862, conf 265.937
iter_i 525

Total time: 1:45:31.647561, iter: 0:00:12.014512, epoch: 3:05:02.772681
[Iteration 525] [learning rate 0.0001] [Total loss 592.01] [img size 640]
level_20 total 1 objects: xy/gt 1.429, wh/gt 0.063, angle/gt 1.396, conf 20.445
level_40 total 11 objects: xy/gt 1.468, wh/gt 0.127, angle/gt 0.911, conf 93.503
level_80 total 44 objects: xy/gt 1.408, wh/gt 0.300, angle/gt 0.684, conf 349.730
iter_i 526
```
the  loss of `conf` are all bigger than 1 even it should be the output of sigmod function
`conf = torch.sigmoid(raw[..., 5])`

**Comment by duanzhiihao** [comment]
Hi, regarding the training log, `conf = torch.sigmoid(raw[..., 5])` is the predicted objectness confidence, while in the log `conf` refers to the loss of the objectness confidence. Sorry for the confusion. https://github.com/duanzhiihao/RAPiD/blob/9567f52a4e8eb443d12e51eb8ad2f8ce3bf9eeb5/models/rapid.py#L305

Regarding the validation error, I'm investigating it and will inform you later.

**Comment by lunasdejavu** [comment]
I tried backbone  dark53 and the result is still the same, I printed the detection results in all progresses

```
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:18<00:00,  9.25s/it]
tps [tensor([], size=(10, 0), dtype=torch.bool), tensor([], size=(10, 0), dtype=torch.bool)]
scores [tensor([]), tensor([])]
accumulating results
accumulate tps tensor([], size=(10, 0), dtype=torch.bool)
tps[:,sortidx] tensor([], size=(10, 0), dtype=torch.bool)
fps tensor([], size=(10, 0), dtype=torch.bool)
tp_sum tensor([], size=(10, 0))
fp_sum tensor([], size=(10, 0))
```
the size (10,0) caused      `   assert ((tp_sum[:,-1] + fp_sum[:,-1]) == num_dt).all()`

**Comment by lunasdejavu** [comment]
I found the problem  , Total Commander change the captital character when I upload the dataset to my  
lab's server.(Lunch000001.jpg to lunch000001.jpg) thank you again!
